server:
  port: 8080

spring:
  # Application
  application:
    name: bank-graphql

  # Datasource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # GraphQL
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      locations: classpath:graphql/
      file-extensions: .graphql,.graphqls

# Swagger-UI custom path
springdoc:
  swagger-ui:
    path: /index.html 